# finops instance scheduler — generated by finops-mcp.
# Starts/stops EC2 and RDS instances whose `Schedule` tag matches a window
# defined below. Review, adjust schedules/timezone as needed, then apply.

locals {
  finops_schedules = {
    "daily-08-18" = { days = [0, 1, 2, 3, 4, 5, 6], start = 8, stop = 18 }
    "mon-fri-07-20" = { days = [0, 1, 2, 3, 4], start = 7, stop = 20 }
    "mon-fri-08-18" = { days = [0, 1, 2, 3, 4], start = 8, stop = 18 }
  }
}

data "archive_file" "finops_scheduler" {
  type        = "zip"
  source_file = "${path.module}/finops_scheduler_lambda.py"
  output_path = "${path.module}/.finops/finops_scheduler_lambda.py.zip"
}

resource "aws_iam_role" "finops_scheduler" {
  name = "finops-instance-scheduler"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Action    = "sts:AssumeRole"
      Effect    = "Allow"
      Principal = { Service = "lambda.amazonaws.com" }
    }]
  })
}

resource "aws_iam_role_policy" "finops_scheduler" {
  name = "finops-instance-scheduler"
  role = aws_iam_role.finops_scheduler.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect = "Allow"
        Action = [
          "ec2:DescribeInstances",
          "ec2:StartInstances",
          "ec2:StopInstances",
          "rds:DescribeDBInstances",
          "rds:ListTagsForResource",
          "rds:StartDBInstance",
          "rds:StopDBInstance",
        ]
        Resource = "*"
      },
      {
        Effect   = "Allow"
        Action   = ["logs:CreateLogGroup", "logs:CreateLogStream", "logs:PutLogEvents"]
        Resource = "arn:aws:logs:*:*:*"
      },
    ]
  })
}

resource "aws_lambda_function" "finops_scheduler" {
  function_name    = "finops-instance-scheduler"
  role             = aws_iam_role.finops_scheduler.arn
  runtime          = "python3.12"
  handler          = "finops_scheduler_lambda.handler"
  filename         = data.archive_file.finops_scheduler.output_path
  source_code_hash = data.archive_file.finops_scheduler.output_base64sha256
  timeout          = 120

  environment {
    variables = {
      SCHEDULES_JSON = jsonencode(local.finops_schedules)
      SCHEDULER_TZ   = "America/New_York"
    }
  }
}

resource "aws_cloudwatch_event_rule" "finops_scheduler" {
  name                = "finops-instance-scheduler"
  schedule_expression = "rate(15 minutes)"
}

resource "aws_cloudwatch_event_target" "finops_scheduler" {
  rule = aws_cloudwatch_event_rule.finops_scheduler.name
  arn  = aws_lambda_function.finops_scheduler.arn
}

resource "aws_lambda_permission" "finops_scheduler" {
  statement_id  = "AllowEventBridge"
  action        = "lambda:InvokeFunction"
  function_name = aws_lambda_function.finops_scheduler.function_name
  principal     = "events.amazonaws.com"
  source_arn    = aws_cloudwatch_event_rule.finops_scheduler.arn
}
