"""finops instance scheduler — starts/stops EC2/RDS instances whose
`Schedule` tag matches a window defined in SCHEDULES_JSON.

Generated by finops-mcp. Runs every 15 minutes via EventBridge.
"""

import datetime
import json
import os

import boto3

try:
    from zoneinfo import ZoneInfo
except ImportError:  # pragma: no cover
    ZoneInfo = None

SCHEDULES = json.loads(os.environ["SCHEDULES_JSON"])
TZ = os.environ.get("SCHEDULER_TZ", "UTC")


def _now():
    if ZoneInfo is not None:
        return datetime.datetime.now(ZoneInfo(TZ))
    return datetime.datetime.utcnow()


def _in_window(sched, now):
    return now.weekday() in sched["days"] and sched["start"] <= now.hour < sched["stop"]


def handler(event, context):
    now = _now()
    actions = []

    ec2 = boto3.client("ec2")
    pages = ec2.get_paginator("describe_instances").paginate(
        Filters=[{"Name": "tag-key", "Values": ["Schedule"]}]
    )
    for page in pages:
        for res in page["Reservations"]:
            for inst in res["Instances"]:
                tags = {t["Key"]: t["Value"] for t in inst.get("Tags", [])}
                sched = SCHEDULES.get(tags.get("Schedule", ""))
                if not sched:
                    continue
                state = inst["State"]["Name"]
                iid = inst["InstanceId"]
                if _in_window(sched, now) and state == "stopped":
                    ec2.start_instances(InstanceIds=[iid])
                    actions.append(f"start ec2 {iid}")
                elif not _in_window(sched, now) and state == "running":
                    ec2.stop_instances(InstanceIds=[iid])
                    actions.append(f"stop ec2 {iid}")

    rds = boto3.client("rds")
    for page in rds.get_paginator("describe_db_instances").paginate():
        for db in page["DBInstances"]:
            arn = db["DBInstanceArn"]
            tags = {t["Key"]: t["Value"]
                    for t in rds.list_tags_for_resource(ResourceName=arn)["TagList"]}
            sched = SCHEDULES.get(tags.get("Schedule", ""))
            if not sched:
                continue
            ident = db["DBInstanceIdentifier"]
            status = db["DBInstanceStatus"]
            if _in_window(sched, now) and status == "stopped":
                rds.start_db_instance(DBInstanceIdentifier=ident)
                actions.append(f"start rds {ident}")
            elif not _in_window(sched, now) and status == "available":
                rds.stop_db_instance(DBInstanceIdentifier=ident)
                actions.append(f"stop rds {ident}")

    print(json.dumps({"time": now.isoformat(), "actions": actions}))
    return {"actions": actions}
